[changelog]
body = """
## What's Changed

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits -%}
- {% if commit.breaking %}[breaking] {% endif %}{{ commit.message | split(pat="\\n") | first | upper_first }}\
{% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}){% endif %}\
{% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/DylanDevelops/tmpo/pull/{{ commit.remote.pr_number }}){% endif %}
{% endfor %}

{% endfor %}
{%- set new_contributors = github.contributors | filter(attribute="is_first_time", value=true) %}
{% if new_contributors | length > 0 %}
## New Contributors
{% for contributor in new_contributors -%}
- [@{{ contributor.username }}](https://github.com/{{ contributor.username }}) made their first contribution!
{% endfor %}
{% endif %}


{% if previous.version %}
**Full Changelog**: https://github.com/DylanDevelops/tmpo/compare/{{ previous.version }}...{{ version }}
{% else %}
**Full Changelog**: https://github.com/DylanDevelops/tmpo/commits/{{ version }}
{% endif %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->✨ Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->🚀 Performance Improvements" },
  { message = "^refactor", group = "<!-- 3 -->🛠️ Refactoring" },
  { message = "^docs?", group = "<!-- 4 -->📚 Documentation" },
  { message = "^(build|ci)", group = "<!-- 5 -->🔧 Build & Dependencies" },
  { message = "^chore", group = "<!-- 6 -->🧹 Maintenance" },
  { message = "^Merge ", skip = true },
]